### ISSUE TITLE
Handling Client->receive() 

### ISSUE THREAD

**Issue by snmatsui** [sirn-se/websocket-php#41]
In 2.x version, the return value of `Connection->pullMessage()` is `Message`, but the return value of `Client->receive()` is set to `Message|null`.
Should I handle the null case?

**Comment by sirn-se** [comment]
No, that's a leftover I missed to change from earlier versions. It always return `Message` instance, or throw Exception if it fails to read.

I will change return type in `v3.x`.
Thanks for pointing this out to me.

**Comment by welpie21** [comment]
Heey, I'm quite new to this library and had a question on the `receive` function.

Since websockets can have responses in random order. the `receive` function is blocking but somehow I get responses in a different order back than that they're executed in.

Is there a way to point the response to the reques that the library provides?

Best regards

**Comment by welpie21** [comment]
I have also a small question but not sure if it's related to a bug or missmanagement of my code. I use the request / response strategy. Every request I make I want to wait for the response, by the time I want to block further code till it has been resolved.

Does the `receive`  function do that for me? If yes I have an issue whereby responses that can take longer initially ( for example auth ) can mix-up between requests.

So for me it goes like this:

1. call a method called `signin` the response should be an array with `{id: <int>, result: <jwt>}`
2. response from signin comes in and the response is: `{id: <int>, result: null}`
3. call a method called `create` the response should be an array with `{id: <int>, result: <array>}`
4. response from create comes in and response is: `{id: <int>, result: <jtw>` 

And I verify this that the server doesn't respond in random order because on other platforms such as Javascript and Python are doing fine with the websocket.

So under here I have dumped 3 variables and it goes in this order: `method`, `payload` and `response`.

**signin**
```php
string(6) "signin"
array(3) {
  ["id"]=>
  int(1)
  ["method"]=>
  string(6) "signin"
  ["params"]=>
  array(1) {
    [0]=>
    array(2) {
      ["user"]=>
      string(4) "root"
      ["pass"]=>
      string(4) "root"
    }
  }
}
string(22) "{"id":1,"result":null}"
```

**create**
```php
.string(6) "create"
array(3) {
  ["id"]=>
  int(1)
  ["method"]=>
  string(6) "create"
  ["params"]=>
  array(2) {
    [0]=>
    string(6) "person"
    [1]=>
    array(2) {
      ["name"]=>
      string(4) "Beau"
      ["age"]=>
      int(30)
    }
  }
}
string(254) "{"id":1,"result":"eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDk5ODk5MTUsIm5iZiI6MTcwOTk4OTkxNSwiZXhwIjoxNzA5OTkzNTE1LCJpc3MiOiJTdXJyZWFsREIiLCJJRCI6InJvb3QifQ.POf1gE17785-rqH7TxoNcidRUNbaJObYBWxGcM23IY78g_T4kBLdWQou9AnAc_2DB0nKEG3jcVo5KtCjmgxXrQ"}"
```

**Comment by sirn-se** [comment]
@welpie21 

Yes, the `receive()` will block further code execution until there's a message to return (or the connection time out).

It will always read from the beginning of the stream, and return complete messages in the order written to stream by server. A message will be considered complete when the last frame of that message have been received. Sometimes a control message may interrupt a content message.

To get more details on what's really going on, you can add a logger to the Client as described here:
https://github.com/sirn-se/websocket-php/blob/v2.1-main/docs/Examples.md#echo-logger

**Comment by welpie21** [comment]
> @welpie21 
> 
> Yes, the `receive()` will block further code execution until there's a message to return (or the connection time out).
> 
> It will always read from the beginning of the stream, and return complete messages in the order written to stream by server. A message will be considered complete when the last frame of that message have been received. Sometimes a control message may interrupt a content message.
> 
> To get more details on what's really going on, you can add a logger to the Client as described here:
> https://github.com/sirn-se/websocket-php/blob/v2.1-main/docs/Examples.md#echo-logger

I will look into this evening. I have a work around to have it in a while loop with some conditionals which fixes the issue.

Will let you know if I have found something.

**Comment by sirn-se** [comment]
Inactive, closing.
