### ISSUE TITLE
Client clearReceiveBuffer() method?

### ISSUE THREAD

**Issue by adelin-mcbsoft** [sirn-se/websocket-php#55]
Hi,
I was thinking that a `clearReceiveBuffer()` method would be very useful.
Consider this case:
You have a socket where you want to receive data every minute, only after you sent some.

To give a basic example:

```
while(true) {
	$client->text('send some data');
	while(!is_null($msg = $client->receive())) {
		$data = $msg->getContent();
		if($data == 'is_the_data_we want')
			break;
	}
	sleep(60);
}
```

The problem is that `$client->receive()` will first bring all the data it had in its buffer (before `$client->text()` was sent to the server), and only after couple of iterations will bring the data we want (meaning, the data the server sent after `$client->text()` was called.

In this situation, there would very useful to have a method which will clear all the contents of the buffer (e.g. something like `$client->clearReceiveBuffer()`) before sending data to the server.

This way, the following iterations of `$client->receive()` will only bring the data received after the buffer was cleared.

_(futhermore, I'm not even aware how big this buffer is in the first place... or how it reacts when it's full, if it truncates the data or not, which part gets truncated, etc.)_

Doing a loop of `$client->receive()` to clear it isn't feasible, since it'll block the code until some message is received.
I was thinking as a workaround to set a very small timeout (e.g. 2 seconds), which will allow the code to continue if no message is received, but it's not the optimal solution.

Let me know what you think about my input,
And thank you for this library btw, you've done a great job!
Good day,
A.

**Comment by sirn-se** [comment]
Hi @adelin-mcbsoft 

Client has no internal buffer(*), it reads from the connection stream - which is a blocking operation. So to "clear" a stream would also be a blocking operation.

I would recommend you have a look on what I've called "subscribe" in the [documentation](https://github.com/sirn-se/websocket-php/blob/v2.2-main/docs/Client.md#subscribe-operation). Instead of explicitly checking/reading from the stream using `receive()`, the stream will run provided callback function when a message has been received. You can then easily filter the messages you're interested in and ignore the rest.

Sloppy example below;

```php
$doRead = false;
$lastRead = 0;
$client = new Client("wss://echo.websocket.org/");
$client
    ->addMiddleware(new CloseHandler())
    ->addMiddleware(new PingResponder())
    ->setTimeout(60)
    ->onText(function (Client $client, Connection $connection, Message $message) {
        if ($doRead) {
            // this is the first received
            $message->getContent();
            $doRead = false;
        }
    })
    ->onTick(function (Client $client, Connection $connection) {
        if (time() > $lastRead + 60) }
            $connection->text('send some data');
            $doRead = true;
            $lastRead = time();
        }
    })
    ->start();
```

(*) = Yes, there actually is a buffer. But it's for fragmented messages, and clearing it would not achieve what you need.

**Comment by sirn-se** [comment]
Inactive, closing
