### ISSUE TITLE
from textalk

### ISSUE THREAD

**Issue by Razorholt** [sirn-se/websocket-php#62]
Hello there!

I've been using the textalk library for quite a while but apparently I have to switch to this one now. This is what I tried but it doesn't work at all:

```
use WebSocket\Client;

function connectToCoinbaseSocket($productIds = ['BTC-USD'], $channels = ['ticker']) {
    $client = new Client('wss://advanced-trade-ws.coinbase.com');
    $subscribeMessage = array_merge([
        'type' => 'subscribe',
        'product_ids' => $productIds,
        'channels' => $channels
    ]);
    $client->send($subscribeMessage);
    while ($client->isConnected()) {
        $message = $client->receive();
        echo $message . "\n";
    }
    $client->close();
}
connectToCoinbaseSocket();
```

It's probably not the right way to handle send() but I'd appreciate it if someone would help me get it fixed. 

Thank you for your help!

-Dan

**Comment by sirn-se** [comment]
Hi @Razorholt 

Version `1.x` of this library is fully compatible with textalk. But I do recommend upgrading, and in your case use the [subscription strategy](https://github.com/sirn-se/websocket-php/blob/v3.0-main/docs/Client.md#subscribe-operation) instead of running manual `receive()`.

There's an obvious error in your code; `$client->send() `expects a string (or `Message` instance).
You probably want to `json_encode` instead of `array_merge`.

**Comment by Razorholt** [comment]
Will give it a try. Thank you so much!
